### ISSUE TITLE
Standard Operator Web API

### ISSUE THREAD

**Issue by stevencox** [NCATS-Tangerine/ros#3]
Incorporate the emerging standard operator web API.

**Comment by stevencox** [comment]
Most recent cut looks like this: 
```

  condition_to_drug:
    doc: |
      Call multiple implementations of workflow-one:modules(one,two) through a common interface.
    code: graph-operator
    args:
      message:
        knowledge_graph:
          nodes: select "$.[*].result_list.[*][*].result_graph.node_list.[*]" from $disease_identifiers
      services:
        - name: rtx
          url: http://localhost:5003/wf1mod1and2
        - name: green
          url: http://localhost:5004/wf1mod1    
```
This interacts with two providers of workflow 1. 

Will discuss w/Patrick and Eric tomorrow.
